language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devops4linuxfernando
  api_key:
    secure: yK/cyqsC+O5I+hp6h9fcLNWpfmzQQaYCzEjj3K6T/RXM9emv+Fca7uDWbBrKqwdH/u5b+4xyUwCZXK6OrogquVmyKC9mzMNVodTU7Scnq+EEBxRfPS8o0QRMB7zU+JIHDKyy70wEVFndXOZWlOEEhUVHsTNUXmmRzPIiLc/ipIO1G/joZdpGzgeU/xCgMz4mzEE1NKB25h+TmHsLEpVBXMOOtZA5K0kBF97AvviOYgdmfrQDtvdqvCLVFOXxRmqM0/JDvNs2E8bkJ4e6rAEDONz8Dw0VGTtubJ5tpKSV8W0I41j2WL/4wRM8yw0mbvwie+iykj7C3AXXaV7WHRFtU2gpngyXF0vOiUlAtVrb83alt2CpgTKSe04w+n9ef6HDvsMjenbScbDNPcXPk3dFaqR+ODJHVvLp5w/YiZFudvuqx9NdHkrJ0ctt72VqGoYl/W6Mk4A193/Bc6vGHIpYZaVjZvKGlwlfmdfUtpAbwF8Qfy+r0lY2km0/9DEl8lJ7gV4NdWHgOJZSqgd4T27KX0wR+tsTvdBiwIWYe90IsS0z+fu8hM92EfQGYADDoqUVyUBQmI777JIcTP3AWEXw1dApS3PQRJY2l+6WeRvhGmh+axQfG+TAa0CZW2CcisSDn7ALJ027flYOD/mlgnLGEIqzaFC3mWfdoP2wb6MTNn8=
